### ISSUE TITLE
Do you still work on this?

### ISSUE THREAD

**Issue by jebedaia360** [ellis-matthew4/XDL#6]
I ask because I working on something similar my self:
https://github.com/jebedaia360/Rakugo
Maybe you want to join?

**Comment by ellis-matthew4** [comment]
I do still work on this. If I can, I'd be happy to help with Rakugo, but this isn't the place to discuss it. Shoot me an email and we can talk about it further.

**Comment by jebedaia360** [comment]
Ok, @ellis-matthew4, but I don't see your mail address anywhere.
